---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: elvis
  name: elvis
spec:
  replicas: 1
  selector:
    matchLabels:
      app: elvis
  template:
    metadata:
      labels:
        app: elvis
    spec:
      containers:
      - image: ghcr.io/caju-rocks/elvis:latest
        name: elvis
