---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: elvis
    environment: dev
  name: elvis
spec:
  replicas: 1
  selector:
    matchLabels:
      app: elvis
  template:
    metadata:
      labels:
        app: elvis
        version: 0.0.2
    spec:
      containers:
      - image: ghcr.io/caju-rocks/elvis:0.0.2
        imagePullPolicy: IfNotPresent
        name: elvis
